/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.esprit.GUI;

import com.esprit.DAO.ProduitDao;
import com.esprit.adapters.ProduitAdapter;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class AffichListeProduit extends javax.swing.JFrame {

    /**
     * Creates new form AffichListeCitoyen
     */
    public AffichListeProduit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jBSupp = new javax.swing.JButton();
        jButRechercher = new javax.swing.JButton();
        jRech = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jBSupp1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jBSupp2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jBSupp.setBackground(new java.awt.Color(255, 255, 255));
        jBSupp.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jBSupp.setText("<< Retour");
        jBSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSuppActionPerformed(evt);
            }
        });
        getContentPane().add(jBSupp);
        jBSupp.setBounds(50, 480, 150, 40);

        jButRechercher.setText("Rechercher");
        jButRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRechercherActionPerformed(evt);
            }
        });
        getContentPane().add(jButRechercher);
        jButRechercher.setBounds(290, 190, 150, 40);

        jRech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRechActionPerformed(evt);
            }
        });
        getContentPane().add(jRech);
        jRech.setBounds(110, 210, 160, 26);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(480, 90, 0, 0);

        jBSupp1.setBackground(new java.awt.Color(255, 255, 255));
        jBSupp1.setText("Supprimer");
        jBSupp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSupp1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBSupp1);
        jBSupp1.setBounds(250, 400, 150, 40);

        jLabel13.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("Liste des citoyens");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(110, 130, 500, 40);

        jBSupp2.setBackground(new java.awt.Color(255, 255, 255));
        jBSupp2.setText("Supprimer");
        jBSupp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSupp2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBSupp2);
        jBSupp2.setBounds(250, 400, 150, 40);

        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 400, 140, 40);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 20, 1060, 700);

        jTable1.setModel(new com.esprit.adapters.ProduitAdapter());
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 254, 970, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSuppActionPerformed
        AddProduit esp=new AddProduit(); 
           esp.setSize(950,640);
           esp.setLocationRelativeTo(null);
           esp.setVisible(true);

    }//GEN-LAST:event_jBSuppActionPerformed

    private void jRechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRechActionPerformed

    private void jButRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRechercherActionPerformed

 
    }//GEN-LAST:event_jButRechercherActionPerformed

    private void jBSupp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSupp1ActionPerformed
 ProduitDao citdao=new ProduitDao();
          
          new ProduitDao().removeProduitById(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString()));
            jTable1.setModel( new ProduitAdapter());
                    JOptionPane.showMessageDialog(null, "Citoyen supprimé avec succes", ":D", JOptionPane.INFORMATION_MESSAGE);    }//GEN-LAST:event_jBSupp1ActionPerformed

    private void jBSupp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSupp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSupp2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AffichListeProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AffichListeProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AffichListeProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AffichListeProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
               ProduitDao citdao=new ProduitDao();
               AffichListeProduit aff= new AffichListeProduit();
               aff.setSize(950,640);
                aff.setVisible(true);
                citdao.findAll();
               
            }
        });
    }
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSupp;
    private javax.swing.JButton jBSupp1;
    private javax.swing.JButton jBSupp2;
    private javax.swing.JButton jButRechercher;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jRech;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
