/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.esprit.GUI;

import com.esprit.DAO.AdminDAO;
import com.esprit.DAO.packDao;
import com.esprit.Util.db_connection;
import com.esprit.entites.image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author snoussi
 */
public class ajou_pack extends javax.swing.JFrame {

    /**
     * Creates new form ajou_pack
     */
      DefaultTableModel    model = new DefaultTableModel();
          Statement stm;
    ResultSet Rs;
        db_connection conn=new db_connection();
      
    public ajou_pack() {
            model.addColumn("Priorit d'affichage");
model.addColumn("nom_pack");
model.addColumn("photo_pack");
        initComponents();
    }
         public void afficher1(){
    try {
   model.setRowCount(0);
    
stm=conn.obtenirconnexion().createStatement();
ResultSet res=stm.executeQuery("Select * from image");
while(res.next()){
model.addRow(new Object[]{res.getInt("id"),res.getString("titre"),res.getString("img")});

}
}catch(SQLException e){System.err.println(e);}

tble.setModel(model);
       }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pack = new javax.swing.JPanel();
        jsupprimerp = new javax.swing.JButton();
        jajouter = new javax.swing.JButton();
        idimg = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tble = new javax.swing.JTable();
        photo = new javax.swing.JLabel();
        Jparcourir = new javax.swing.JButton();
        jTfImage = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTfNompack = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack.setBackground(new java.awt.Color(255, 255, 255));
        pack.setLayout(null);

        jsupprimerp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/supprimer_1.PNG"))); // NOI18N
        jsupprimerp.setText("Supprimer");
        jsupprimerp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsupprimerpActionPerformed(evt);
            }
        });
        pack.add(jsupprimerp);
        jsupprimerp.setBounds(460, 220, 90, 40);

        jajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/ajouter.png"))); // NOI18N
        jajouter.setText("Ajouter");
        jajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jajouterActionPerformed(evt);
            }
        });
        pack.add(jajouter);
        jajouter.setBounds(380, 280, 150, 36);
        pack.add(idimg);
        idimg.setBounds(460, 290, 59, 20);

        tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbleMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tble);

        pack.add(jScrollPane3);
        jScrollPane3.setBounds(440, 30, 430, 120);
        pack.add(photo);
        photo.setBounds(450, 220, 110, 60);

        Jparcourir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/parcoure.PNG"))); // NOI18N
        Jparcourir.setText("Parcourir");
        Jparcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JparcourirActionPerformed(evt);
            }
        });
        pack.add(Jparcourir);
        Jparcourir.setBounds(170, 280, 150, 40);

        jTfImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfImageActionPerformed(evt);
            }
        });
        pack.add(jTfImage);
        jTfImage.setBounds(230, 230, 143, 32);

        jLabel10.setText("Image");
        pack.add(jLabel10);
        jLabel10.setBounds(90, 240, 86, 23);

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        pack.add(id);
        id.setBounds(220, 170, 143, 28);

        jLabel11.setText("Prioriter d'affichage");
        pack.add(jLabel11);
        jLabel11.setBounds(80, 180, 94, 14);

        jLabel12.setText("Nom Pack");
        pack.add(jLabel12);
        jLabel12.setBounds(120, 90, 70, 20);

        jTfNompack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfNompackActionPerformed(evt);
            }
        });
        pack.add(jTfNompack);
        jTfNompack.setBounds(210, 80, 143, 32);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pack.add(jButton1);
        jButton1.setBounds(290, 390, 110, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pack, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pack, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsupprimerpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsupprimerpActionPerformed

        packDao a=new packDao();

        a.supprimer(id.getText());
        afficher1();
        ////  packDao pa = new packDao();
        //  pack cp = new pack();
        //  pa.supprimerpack(cp);

        JOptionPane.showMessageDialog(null, "pack Supprim�e", "Information",JOptionPane.INFORMATION_MESSAGE );
        afficher1();
    }//GEN-LAST:event_jsupprimerpActionPerformed

    private void jajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jajouterActionPerformed
        //a verifierr
        FileInputStream fileInputStream=null;
        String path = jTfImage.getText();

        File file = new File(path);
        byte[] bFile = new byte[(int) file.length()];

        try {
            //convert file into array of bytes

            fileInputStream = new FileInputStream(file);
            fileInputStream.read(bFile);
            fileInputStream.close();

        }catch(IOException e){
        }

        //  String jBottonText = groupButton1( );

        // if ( "pack".equals(jBottonText) )
        // {
            image cp = new image();
            cp.setTitre(jTfNompack.getText());
            cp.setId(id.getText());

            //  String path = jTfImage.getText();
            File imageC=new File(path);
            BufferedImage originalImage = null;
            try {
                originalImage = ImageIO.read(imageC);
            } catch (IOException ex) {
                Logger.getLogger(image.class.getName()).log(Level.SEVERE, null, ex);
            }
            ByteArrayOutputStream baos=new ByteArrayOutputStream();
            try {
                ImageIO.write(originalImage, "jpg", baos );
            } catch (IOException ex) {
                Logger.getLogger(image.class.getName()).log(Level.SEVERE, null, ex);
            }
            byte[] imageInByte=baos.toByteArray();
            cp.setPhoto_pack(imageInByte);

            //  pack cpd = new pack();
            AdminDAO r = new AdminDAO();
            r.ajouterpacker(cp);
            //  cpd.ajouterpacker(cp);

            JOptionPane.showMessageDialog(null, "pack ajouter", "Information",JOptionPane.INFORMATION_MESSAGE );
            //   }
        afficher1();
    }//GEN-LAST:event_jajouterActionPerformed

    private void tbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbleMouseClicked
        try {  int i=tble.getSelectedRow();

            deplace(i);
            //sa si quant on choisir un nom dans le tableau il va afficher sur les fieldtext
        }
        catch (Exception e){JOptionPane.showMessageDialog(null,"erreur selectionne\n"+e.getMessage());

        }
    }//GEN-LAST:event_tbleMouseClicked

    private void JparcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JparcourirActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
        chooser.addChoosableFileFilter(filter);

        int result = chooser.showSaveDialog(null);
        // chooser.showOpenDialog(null);

        File f = chooser.getSelectedFile();
        String path=f.getAbsolutePath();
        //Lpath.setIcon(ResizeImage(path));
        jTfImage.setText(path);
    }//GEN-LAST:event_JparcourirActionPerformed

    private void jTfImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfImageActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void jTfNompackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfNompackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfNompackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
             packDao a=new packDao();

        a.modifier(id.getText(), idimg.getText());
      afficher1();
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
private void deplace(int i){
     try {     //i represente les ligne 
//   
     id.setText(model.getValueAt (i, 0).toString());
// 
//       txtno.setText(model.getValueAt (i, 1).toString());
//       
//    
   jTfNompack.setText(model.getValueAt (i, 1).toString());
     jTfImage.setText(model.getValueAt (i, 2).toString());
      idimg.setText(model.getValueAt (i, 0).toString());
//     txtma.setText(model.getValueAt (i, 4).toString());
       //txtbr.setSelectedItem(model.getValueAt(i,5).toString());
     }catch (Exception e){ JOptionPane.showMessageDialog(null,"erreur de deplacement de message !!!!! "+e.getMessage());     }}
      
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajou_pack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajou_pack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajou_pack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajou_pack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajou_pack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jparcourir;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idimg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTfImage;
    private javax.swing.JTextField jTfNompack;
    private javax.swing.JButton jajouter;
    private javax.swing.JButton jsupprimerp;
    private javax.swing.JPanel pack;
    private javax.swing.JLabel photo;
    private javax.swing.JTable tble;
    // End of variables declaration//GEN-END:variables
}
