/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.GUI;

//import egov.dao.classes.AgentDao;
//import egov.dao.classes.CitoyenDao;
//import egov.entities.Agent;
import com.esprit.DAO.ProduitDao;
import com.esprit.adapters.ProduitAdapter;
import com.esprit.entites.Produit;
import java.awt.Color;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.parser.TokenType;

/**
 *
 * @author user
 */
public class EspaceResponsable2 extends javax.swing.JFrame {

    /**
     * Creates new form EspaceAdminn
     */
    public EspaceResponsable2() {
        initComponents();
        this.getContentPane().setBackground(new Color(227,157,171));
        //jTabbedPane1.getComponentPopupMenu().setBackground(Color.red);
        jTabbedPane2.setBackground(Color.RED);
        //jTabbedPane2.setBackground(Color.red);
       // jTabbedPane2.setBackground(Color.RED);
        jTabbedPane2.setBackgroundAt(1,Color.RED);
        jPanel1.add(jTabbedPane2);
jPanel1.setBackground(Color.WHITE);
                
    }
          
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        f = new javax.swing.JTextField();
        g = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        IMessage = new javax.swing.JLabel();
        g6 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        g7 = new javax.swing.JTextField();
        g8 = new javax.swing.JTextField();
        g9 = new javax.swing.JTextField();
        g12 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jTextSearch = new javax.swing.JTextField();
        search_butn = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        g1 = new javax.swing.JTextField();
        f1 = new javax.swing.JTextField();
        e1 = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();
        c1 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        h1 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        g2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        g3 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        g4 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        g5 = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jLabel19.setText("jLabel19");

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Produit");
        setBackground(new java.awt.Color(227, 157, 171));
        setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(102, 0, 204));
        jTabbedPane1.setForeground(new java.awt.Color(255, 0, 51));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setToolTipText("Produit");

        jPanel1.setLayout(null);

        jTabbedPane2.setBackground(new java.awt.Color(255, 51, 51));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jTabbedPane2.setForeground(new java.awt.Color(227, 157, 171));
        jTabbedPane2.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 51, 51));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/image/23314007-3D-r-alistes-illustration-vectorielle-d-un-bouton-en-m-tal-carr-avec-un-panier-ic-ne-de-suppression--Banque-d'images (1).jpg"))); // NOI18N
        jButton4.setText("supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable2.setModel(new com.esprit.adapters.ProduitAdapter());
        jScrollPane5.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jButton4)))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton4)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Supprimer produit", jPanel4);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("designation");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(360, 50, 74, 18);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("taille");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(360, 100, 60, 18);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("reference");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 150, 70, 18);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("couleur");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 200, 80, 14);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("marque");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 50, 70, 18);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("description");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 100, 80, 18);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("etat");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(360, 150, 40, 26);

        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        jPanel3.add(a);
        a.setBounds(120, 40, 180, 30);

        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        jPanel3.add(b);
        b.setBounds(120, 90, 180, 30);
        jPanel3.add(c);
        c.setBounds(120, 140, 180, 30);

        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        jPanel3.add(d);
        d.setBounds(120, 190, 180, 30);
        jPanel3.add(e);
        e.setBounds(440, 40, 180, 30);
        jPanel3.add(f);
        f.setBounds(440, 90, 180, 30);

        g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gActionPerformed(evt);
            }
        });
        jPanel3.add(g);
        g.setBounds(780, 30, 180, 30);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("prixvente");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(690, 40, 70, 20);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/image/add_256 copie.png"))); // NOI18N
        jButton3.setText("Ajouter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(270, 310, 145, 60);

        IMessage.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(IMessage);
        IMessage.setBounds(612, 363, 276, 23);

        g6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g6ActionPerformed(evt);
            }
        });
        jPanel3.add(g6);
        g6.setBounds(440, 140, 180, 30);

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 0, 0));
        jLabel24.setText("marque");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(690, 90, 70, 20);

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 0, 0));
        jLabel25.setText("disponible");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(690, 140, 80, 20);

        jLabel26.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 0, 0));
        jLabel26.setText("image");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(690, 190, 80, 20);

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 0, 0));
        jLabel28.setText("prixdachat");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(360, 190, 70, 20);

        g7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g7ActionPerformed(evt);
            }
        });
        jPanel3.add(g7);
        g7.setBounds(780, 90, 180, 30);

        g8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g8ActionPerformed(evt);
            }
        });
        jPanel3.add(g8);
        g8.setBounds(780, 140, 180, 30);

        g9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g9ActionPerformed(evt);
            }
        });
        jPanel3.add(g9);
        g9.setBounds(780, 180, 180, 30);

        g12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g12ActionPerformed(evt);
            }
        });
        jPanel3.add(g12);
        g12.setBounds(440, 180, 180, 30);

        jTabbedPane2.addTab("Ajout produit", jPanel3);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jTextSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSearchActionPerformed(evt);
            }
        });

        search_butn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/image/rechercher-icone-8124-32.png"))); // NOI18N
        search_butn.setText("search");
        search_butn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_butnActionPerformed(evt);
            }
        });

        jTable1.setModel(new com.esprit.adapters.ProduitAdapter());
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane6.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jTextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(search_butn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(638, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(437, 437, 437)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(273, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_butn))
                .addContainerGap(291, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab(" recherche produit ", jPanel6);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(227, 157, 171));
        jLabel10.setText("description");

        jLabel11.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(227, 157, 171));
        jLabel11.setText("reference");

        jLabel12.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(227, 157, 171));
        jLabel12.setText("couleur");

        jLabel13.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(227, 157, 171));
        jLabel13.setText("designation");

        jLabel14.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(227, 157, 171));
        jLabel14.setText("taille");

        jLabel15.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(227, 157, 171));
        jLabel15.setText("etat");

        jLabel16.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(227, 157, 171));
        jLabel16.setText("prixdachat");

        jLabel17.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(227, 157, 171));
        jLabel17.setText("marque");

        jButtonUpdate.setFont(new java.awt.Font("Nueva Std", 1, 13)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 51, 51));
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/image/refresh_button_link_save_submit_search_pause_icon copie.png"))); // NOI18N
        jButtonUpdate.setText("update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(227, 157, 171));
        jLabel20.setText("id");

        jTable4.setModel(new com.esprit.adapters.ProduitAdapter());
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTable4);

        jLabel21.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(227, 157, 171));
        jLabel21.setText("prixvente");

        jLabel22.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(227, 157, 171));
        jLabel22.setText("disponible");

        jLabel23.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(227, 157, 171));
        jLabel23.setText("image");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 639, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addGap(275, 275, 275))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel23)
                                .addGap(61, 61, 61)
                                .addComponent(g5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(g1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(16, 16, 16)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(g4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addGap(21, 21, 21))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(e1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74)
                                .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 53, Short.MAX_VALUE)))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(g5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18))
        );

        g2.getAccessibleContext().setAccessibleName("");

        jTabbedPane2.addTab("update produit", jPanel5);

        jTabbedPane2.setSelectedIndex(1);

        jPanel1.add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 0, 1016, 500);

        jTabbedPane1.addTab("Produit", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 60, 970, 660);

        button1.setBackground(new java.awt.Color(255, 153, 153));
        button1.setFont(new java.awt.Font("Nueva Std", 1, 13)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 0, 51));
        button1.setLabel("Sign out");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(673, 10, 69, 45);
        button1.getAccessibleContext().setAccessibleName("sign out");

        jLabel1.setFont(new java.awt.Font("Myanmar MN", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Espace Responsable");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(223, 22, 260, 32);

        jLabel27.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/image/logo copie.png"))); // NOI18N
        jLabel27.setText("TunisiaMall");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(0, 0, 260, 50);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/image/logout copie.png"))); // NOI18N
        getContentPane().add(jLabel29);
        jLabel29.setBounds(620, 10, 107, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
      Home aut=  new Home();
        aut.setSize(940, 640);
              
               aut.setVisible(true);
               aut.setLocationRelativeTo(null);
    }//GEN-LAST:event_button1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ProduitDao agdao = new ProduitDao();

        new ProduitDao().removeProduitById(Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString()));

        jTable2.setModel(new ProduitAdapter());
        jTable1.setModel(new ProduitAdapter());
        jTable4.setModel(new ProduitAdapter());

        JOptionPane.showMessageDialog(null, "Agent supprimé avec succes", ":D", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!a.getText().trim().equals("")) {
            String v1 = a.getText();
            String v2 = b.getText();
            String r = c.getText();
            //int v3 = Integer.parseInt(r);
            String r2 = d.getText();

            String v5 = e.getText();
            String v6 = f.getText();
            String v7 = g6.getText();
            String v8 = g12.getText();
            String v9 = g.getText();
            String v10 = g7.getText();
            String v11 = g8.getText();
            String v12 = g9.getText();
            //Object u = combo.getSelectedItem();
           // String v8 = u.toString();

            ProduitDao agentDao = new ProduitDao();
            Produit pr = new Produit();
            pr.setMarque(v1);
            
            pr.setDescription(v2);
            pr.setReference(r);
            pr.setCouleur(r2);
            pr.setDesignation(v5);
            pr.setTaille(v6);
           pr.setEtat(Boolean.valueOf(v6));
           pr.setPrixdachat(Float.valueOf(v8));
           pr.setPrixvente(Float.valueOf(v9));
           pr.setMarque(v10);
            pr.setDisponible(v11);
           pr.setimg(v12);
           
            agentDao.addProduit(pr);
            JOptionPane.showMessageDialog(null, "Agent ajouté avec succes", ":D", JOptionPane.INFORMATION_MESSAGE);
            jTable2.setModel(new ProduitAdapter());
            jTable1.setModel(new ProduitAdapter());
            jTable4.setModel(new ProduitAdapter());

            a.setText("");
            b.setText("");
            c.setText("");
            d.setText("");
            e.setText("");
            f.setText("");
            g.setText("");
            

            
            g6.setText("");
            g12.setText("");
            
            g7.setText("");
           g8.setText("");
            g9.setText("");

            System.out.println("utiliseuur créé");
        } else {
            IMessage.setText(" marque 5aliteha fergha 7ot esmaha ;)  ");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        h1.setText(jTable4.getValueAt(jTable4.getSelectedRow(), 0).toString());
        a1.setText(jTable4.getValueAt(jTable4.getSelectedRow(), 1).toString());
        b1.setText(jTable4.getValueAt(jTable4.getSelectedRow(), 2).toString());
        c1.setText(jTable4.getValueAt(jTable4.getSelectedRow(), 3).toString());
        Produit produit =new ProduitDao().findProduitById(Integer.parseInt(h1.getText()));
        d1.setText(produit.getDesignation());
        e1.setText(produit.getTaille());
        g1.setText(produit.isEtat()+"");
        f1.setText(produit.getPrixdachat()+"");
        g3.setText(produit.getPrixvente()+"");
        g4.setText(produit.getMarque()+"");
        g2.setText(produit.getDisponible()+"");
         g5.setText(produit.getImg()+"");
        //combo1.setSelectedItem(jTable4.getValueAt(jTable4.getSelectedRow(), 8).toString());
    }//GEN-LAST:event_jTable4MouseClicked

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        if (!a1.getText().trim().equals("")) {
            String r0 = h1.getText();
            int v0 = Integer.parseInt(r0);
            String v1 = a1.getText();
            String v2 = b1.getText();
            String r = c1.getText();
            String designation = d1.getText();
            String Taille = e1.getText();
            String Etat= g1.getText();
            String Prixdachat=f1.getText();
            String Prixvente=g3.getText();
            String Marque=g4.getText();
            String Disponible=g2.getText();
            String Img=g5.getText();
           
            ProduitDao produitDao = new ProduitDao();
            Produit pr = new Produit();
            pr.setId(v0);
            pr.setDescription(v1);
            pr.setReference(v2);
            pr.setCouleur(r);                    
                pr.setDesignation(designation);
                pr.setTaille(Taille);
                pr.setEtat(Boolean.valueOf(Etat));
                pr.setPrixdachat(Float.valueOf(Prixdachat));
                pr.setMarque(Marque);
                pr.setPrixvente(Float.valueOf(Prixvente));
                
                pr.setDisponible(Disponible);
                pr.setimg(Img);
               // ???????????????? p.setQuantit(resultat.getInt(15));
            /*ag.setALogin(v1);
            ag.setAPassword(v2);
            ag.setCin(v3);
            ag.setDateCin(r2);
            ag.setEmail(v5);
            ag.setNom(v6);
            ag.setPrenom(v7);
            ag.setType(v8);
            ag.setId(v0);*/
            produitDao.updateProduit(pr);
            JOptionPane.showMessageDialog(null, "Agent modifié avec succes", ":D", JOptionPane.INFORMATION_MESSAGE);
            jTable2.setModel(new ProduitAdapter());
            jTable1.setModel(new ProduitAdapter());
            jTable4.setModel(new ProduitAdapter());

            a1.setText("");
            b1.setText("");
            c1.setText("");
            d1.setText("");
            e1.setText("");
            f1.setText("");
            g1.setText("");
            h1.setText("");
            d1.setText("");
        e1.setText("");
        g1.setText("");
        f1.setText("");
        g3.setText("");
        g4.setText("");
        g2.setText("");
         g5.setText("");

            System.out.println("utiliseuur modifié");
        } else {
            IMessage.setText(" ");
        }

    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void search_butnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_butnActionPerformed
        // TODO add your handling code here:
        // jTable1.setModel(new ProduitAdapter(new ProduitDao().findProduitByCouleur(jTextSearch.getText())));
        if (!jTextSearch.getText().equals("")) {

            jTable1.setModel(new ProduitAdapter(new ProduitDao().getAllByKey(jTextSearch.getText())));
            //jScrollPane1.setViewportView(TablePorteur);
        } else {

            showMessageDialog(this, "Vous devez ecrire quelque chose", "Attention", JOptionPane.INFORMATION_MESSAGE);
            jTable1.setModel(new ProduitAdapter());
        }
        jTextSearch.setText("");
    }//GEN-LAST:event_search_butnActionPerformed

    private void jTextSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSearchActionPerformed

    private void g6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g6ActionPerformed

    private void g7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g7ActionPerformed

    private void g8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g8ActionPerformed

    private void g9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g9ActionPerformed

    private void g12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EspaceResponsable2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EspaceResponsable2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EspaceResponsable2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspaceResponsable2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EspaceResponsable2 e=new EspaceResponsable2();
                e.setSize(950, 640);
              
               e.setVisible(true);
               e.setLocationRelativeTo(null);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMessage;
    private javax.swing.JTextField a;
    private javax.swing.JTextField a1;
    private javax.swing.JTextField b;
    private javax.swing.JTextField b1;
    private java.awt.Button button1;
    private javax.swing.JTextField c;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField d;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField e;
    private javax.swing.JTextField e1;
    private javax.swing.JTextField f;
    private javax.swing.JTextField f1;
    private javax.swing.JTextField g;
    private javax.swing.JTextField g1;
    private javax.swing.JTextField g12;
    private javax.swing.JTextField g2;
    private javax.swing.JTextField g3;
    private javax.swing.JTextField g4;
    private javax.swing.JTextField g5;
    private javax.swing.JTextField g6;
    private javax.swing.JTextField g7;
    private javax.swing.JTextField g8;
    private javax.swing.JTextField g9;
    private javax.swing.JTextField h1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextSearch;
    private javax.swing.JButton search_butn;
    // End of variables declaration//GEN-END:variables
}
