/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.GUI;

import com.esprit.DAO.CartefideliteDao;
import com.esprit.IDAO.ICartefideliteDAO;
import com.esprit.Util.MyConnexion;
import com.esprit.entites.Cartefidelite;
import java.awt.print.PrinterException;
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import javax.swing.UIManager;

/**
 *
 * @author kammoun
 */
public class GestionCarteFidelite extends javax.swing.JFrame {
Connection connection;
    PreparedStatement pst;
    ResultSet rs;
    Cartefidelite carte = new Cartefidelite();
ICartefideliteDAO dao2 = new CartefideliteDao();
    /**
     * Creates new form GestionCarteFidelite
     */
    public GestionCarteFidelite() {
 connection =(MyConnexion.getInstance());
        initComponents();
        afficher();
      JOptionPane.showMessageDialog(rootPane, imessage, null, WIDTH);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        case3 = new com.toedter.calendar.JCalendar();
        case2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        case1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        rechercher = new javax.swing.JTextField();
        bupdate = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bajouter = new javax.swing.JButton();
        bsupprimer = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        imessage = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setText("id carte:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));
        jPanel1.add(case3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        case2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case2ActionPerformed(evt);
            }
        });
        jPanel1.add(case2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 150, 30));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setText("Date de Création:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));
        jPanel1.add(case1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 130, 30));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel6.setText("nombre des points:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdCarte", "Nombre de point", "Date Creation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, 410, 310));

        rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherActionPerformed(evt);
            }
        });
        rechercher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rechercherKeyReleased(evt);
            }
        });
        jPanel1.add(rechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 140, 170, 30));

        bupdate.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        bupdate.setText("modifier");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });
        jPanel1.add(bupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 250, -1));

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton2.setText("imprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 250, -1));

        bajouter.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        bajouter.setText("ajouter");
        bajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajouterActionPerformed(evt);
            }
        });
        jPanel1.add(bajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 250, 40));

        bsupprimer.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        bsupprimer.setText("supprimer");
        bsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsupprimerActionPerformed(evt);
            }
        });
        jPanel1.add(bsupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 320, 260, -1));

        jButton4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton4.setText("retour");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 250, -1));

        imessage.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        imessage.setForeground(new java.awt.Color(255, 0, 0));
        imessage.setText("                                  WELCOME");
        jPanel1.add(imessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 330, 60));

        jTextField1.setBackground(new java.awt.Color(255, 0, 0));
        jTextField1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jTextField1.setText("Gestion carte de fidélite");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 280, 30));

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton1.setText("reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 250, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel4.setText("rechercher:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/resp2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1320, 570));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsupprimerActionPerformed
        DefaultTableModel model=(DefaultTableModel) table.getModel();
        
      
          if(table.getSelectedRow()==-1){
           if(table.getRowCount()==0){
              JOptionPane.showMessageDialog(null, "le tableau est vide");

           }else{
              JOptionPane.showMessageDialog(null, "obligation de sélectionner une carte");

           }
           }else{
              String id = table.getValueAt( table.getSelectedRow(),0).toString();
        carte.setIdCarteFidelite(parseInt(id));
        dao2.deleteCartefidelite(carte);
        
                   model.removeRow(table.getSelectedRow());
                   
                   }
        
    }//GEN-LAST:event_bsupprimerActionPerformed

    private void bajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajouterActionPerformed
       carte.setIdCarteFidelite(parseInt( case1.getText()));
        carte.setNombrePointFidele(parseInt(case2.getText()));
        carte.setDateCreationCarteFidelite(new java.sql.Date(case3.getDate().getTime()));
       


        dao2.insertCartefidelite(carte);
        imessage.setText("");
        DefaultTableModel model=(DefaultTableModel) table.getModel();
        if(!case1.getText().trim().equals("")){
        model.addRow(new Object[]{case1.getText(),case2.getText(),case3.getDate()});
       
        }else{
            imessage.setText("Il faut entrer le nom du client !!!");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_bajouterActionPerformed

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed

         if(table.getSelectedRow()==-1){
           if(table.getRowCount()==0){
              JOptionPane.showMessageDialog(null, "le tableau est vide");

           }else{
              JOptionPane.showMessageDialog(null, "obligation de sélectionner une carte");

           }
           }else{
        String id = table.getValueAt( table.getSelectedRow(),0).toString();
       bupdate.setVisible(true);
        
        carte.setIdCarteFidelite(parseInt(case1.getText()));
        carte.setNombrePointFidele(parseInt(case2.getText()));
        carte.setDateCreationCarteFidelite((new java.sql.Date(case3.getDate().getTime())));
        dao2.updateCartefidelite(carte);
       
        DefaultTableModel model=(DefaultTableModel) table.getModel();
        
        model.setValueAt(case1.getText(), table.getSelectedRow(), 0);
        model.setValueAt(case2.getText(), table.getSelectedRow(), 1);
        model.setValueAt(case3.getDate(), table.getSelectedRow(), 2);
        JOptionPane.showMessageDialog(null, "modification réussite");
       
        if(table.getSelectedRowCount()==0){
            JOptionPane.showMessageDialog(null, "Selectionner un utilisateur !");}

        }
    }//GEN-LAST:event_bupdateActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        
           int i=table.getSelectedRow();
           TableModel model=table.getModel();
           case1.setText(model.getValueAt(i, 0).toString());
           case2.setText(model.getValueAt(i, 1).toString());
           case3.setDate((Date) model.getValueAt(i, 2));
           
    }//GEN-LAST:event_tableMouseClicked

    private void rechercherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rechercherKeyReleased
         String query=rechercher.getText().toLowerCase();
        filter(query);
    }//GEN-LAST:event_rechercherKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        case1.setText("");
        case2.setText("");
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try {
            MessageFormat header=new MessageFormat("Carte ");
            MessageFormat footer=new MessageFormat("Page{0,number,integer}");
            table.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(GestionCarteFidelite.class.getName()).log(Level.SEVERE, null, ex);
           
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void case2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_case2ActionPerformed

    private void rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercherActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       this.setVisible(false);
//        tn.Gui.AceuilResponsableBoutique ab=new tn.Gui.AceuilResponsableBoutique();
//       ab.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed
public void filter(String query){
        
        DefaultTableModel model=(DefaultTableModel) table.getModel();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel> (model);
        table.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
    public void afficher(){
        ArrayList<Cartefidelite> cartes=dao2.DisplayAllCartefidelite();
        DefaultTableModel model=(DefaultTableModel) table.getModel();
        for(Cartefidelite cartee : cartes){model.addRow(new Object[]{cartee.getIdCarteFidelite(),cartee.getNombrePointFidele(),cartee.getDateCreationCarteFidelite()});
    }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
                UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionCarteFidelite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionCarteFidelite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionCarteFidelite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionCarteFidelite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            
            GestionCarteFidelite es=new GestionCarteFidelite();
                es.setSize(1308,566);
                es.setLocationRelativeTo(null);
                es.setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bajouter;
    private javax.swing.JButton bsupprimer;
    private javax.swing.JButton bupdate;
    private javax.swing.JTextField case1;
    private javax.swing.JTextField case2;
    private com.toedter.calendar.JCalendar case3;
    private javax.swing.JLabel imessage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField rechercher;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

   
}
