



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.esprit.GUI;

/**
 *
 * @author snoussi
 */
public class Mot_passe_oublier extends javax.swing.JFrame {

    /**
     * Creates new form Mot_passe_oublier
     */
    public Mot_passe_oublier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        registerr = new javax.swing.JButton();
        login = new javax.swing.JButton();
        new_pwd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(392, 246));
        getContentPane().setLayout(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(11, 80, 340, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/layout mot passe oublier.PNG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 392, 216);

        registerr.setText("register");
        registerr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerrActionPerformed(evt);
            }
        });
        getContentPane().add(registerr);
        registerr.setBounds(10, 20, 73, 23);

        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(90, 20, 63, 23);

        new_pwd.setText("new password");
        new_pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_pwdActionPerformed(evt);
            }
        });
        getContentPane().add(new_pwd);
        new_pwd.setBounds(230, 130, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        
        Login l=new Login();
            l.setVisible(true);
            this.hide();
    }//GEN-LAST:event_loginActionPerformed

    private void registerrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerrActionPerformed
        // TODO add your handling code here:
         Register1 r=new Register1();
            r.setVisible(true);
            this.hide();
        
    }//GEN-LAST:event_registerrActionPerformed

    private void new_pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_pwdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mot_passe_oublier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mot_passe_oublier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mot_passe_oublier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mot_passe_oublier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mot_passe_oublier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton login;
    private javax.swing.JButton new_pwd;
    private javax.swing.JButton registerr;
    // End of variables declaration//GEN-END:variables
}
