package com.esprit.GUI;

import javax.swing.ImageIcon;
import com.esprit.DAO.AdminDAO;
import com.esprit.DAO.BoutiqueDao;
import com.esprit.DAO.ProduitDao;
import com.esprit.DAO.packDao;
import com.esprit.IDAO.IBoutiqueDao;
import com.esprit.Util.db_connection;
import com.esprit.adapters.BoutiqueAdapter;
import com.esprit.adapters.ProduitAdapter;
import com.esprit.entites.Boutique;
import com.esprit.entites.Produit;
import com.esprit.entites.image;
import com.esprit.entites.fos_user;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import javax.swing.UIManager;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author pc
 */
public class Page_resp_12n extends javax.swing.JFrame {

    /**
     * Creates new form Respensable_page
     */
    Timer tm;
    int x = 0;
    Statement stm;
    ResultSet Rs;
    db_connection conn = new db_connection();
    DefaultTableModel model = new DefaultTableModel();
   
    //Images Path In Array
  

    public Page_resp_12n() {
        
        initComponents();

       p.show();
       jPanel5.hide();
      
         jPanel3.hide();
         jPanel4.hide();
         jPanel6.hide();

       
      
       
    }

    //create a function to resize the image 

    public void SetImageSize(int i) {
       
    
    }

    public void afficher1() {
        try {
            model.setRowCount(0);
            stm = conn.obtenirconnexion().createStatement();
            ResultSet res = stm.executeQuery("Select * from pack");
            while (res.next()) {
                model.addRow(new Object[]{res.getInt("id_pack"), res.getString("Nom_pack"), res.getString("photo_pack")});

            }
        } catch (SQLException e) {
            System.err.println(e);
        }

   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        stat_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        search_butn = new javax.swing.JButton();
        stat_btn1 = new javax.swing.JButton();
        stat_btn2 = new javax.swing.JButton();
        jTextSearch = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Dispo1 = new javax.swing.JTextField();
        PrAchat = new javax.swing.JTextField();
        size = new javax.swing.JTextField();
        designation22 = new javax.swing.JTextField();
        couleur = new javax.swing.JTextField();
        reference = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        dispo2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        PriVente = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        marque = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        image = new javax.swing.JTextField();
        IMessage = new javax.swing.JLabel();
        p = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        imageAccProdis = new javax.swing.JLabel();
        imag = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        f = new javax.swing.JTextField();
        g = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        IMessage1 = new javax.swing.JLabel();
        g6 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        g7 = new javax.swing.JTextField();
        g8 = new javax.swing.JTextField();
        g9 = new javax.swing.JTextField();
        g12 = new javax.swing.JTextField();
        addImage = new javax.swing.JButton();
        jLImage = new javax.swing.JLabel();
        pic3 = new javax.swing.JLabel();
        panel_stat = new javax.swing.JPanel();
        panel_image_deroulante = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jTextSearch1 = new javax.swing.JTextField();
        search_butn1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/imageResp/Reourner.png"))); // NOI18N
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 255, 63));

        stat_btn.setBackground(new java.awt.Color(255, 153, 255));
        stat_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        stat_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/imageResp/suppNoir.png"))); // NOI18N
        stat_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        stat_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stat_btnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stat_btnMouseEntered(evt);
            }
        });
        stat_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stat_btnActionPerformed(evt);
            }
        });
        jPanel1.add(stat_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 255, 63));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/imageResp/AfficherN.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 255, 63));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/imageResp/modiNoir.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 255, 63));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/imageResp/AjouterNoir.png"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 255, 63));

        search_butn.setBackground(new java.awt.Color(0, 0, 0));
        search_butn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search-icon copie.png"))); // NOI18N
        search_butn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        search_butn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_butnActionPerformed(evt);
            }
        });
        jPanel1.add(search_butn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 20, 40, 20));

        stat_btn1.setBackground(new java.awt.Color(255, 153, 255));
        stat_btn1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        stat_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/imageResp/RechercherN.png"))); // NOI18N
        stat_btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        stat_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stat_btn1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stat_btn1MouseEntered(evt);
            }
        });
        stat_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stat_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(stat_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 255, 63));

        stat_btn2.setBackground(new java.awt.Color(255, 153, 255));
        stat_btn2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        stat_btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/imageResp/stat.png"))); // NOI18N
        stat_btn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        stat_btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stat_btn2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stat_btn2MouseEntered(evt);
            }
        });
        stat_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stat_btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(stat_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 255, 63));

        jTextSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSearchActionPerformed(evt);
            }
        });
        jPanel1.add(jTextSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, 160, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel11.setText("Description");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(20, 80, 70, 16);

        jLabel12.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel12.setText("Reference");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(25, 118, 80, 16);

        jLabel13.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel13.setText("Couleur");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(25, 162, 60, 16);

        jLabel14.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel14.setText("Designation");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(25, 206, 80, 16);

        jLabel15.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel15.setText("Taille");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(25, 246, 60, 20);

        jLabel16.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel16.setText("Disponible ");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(25, 287, 67, 16);

        jLabel17.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel17.setText("Prix d'achat ");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(30, 320, 80, 16);

        jLabel18.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel18.setText("Marque");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(30, 380, 47, 16);
        jPanel5.add(Dispo1);
        Dispo1.setBounds(138, 277, 240, 26);
        jPanel5.add(PrAchat);
        PrAchat.setBounds(140, 310, 240, 26);
        jPanel5.add(size);
        size.setBounds(138, 241, 240, 26);
        jPanel5.add(designation22);
        designation22.setBounds(138, 197, 240, 26);
        jPanel5.add(couleur);
        couleur.setBounds(138, 153, 240, 26);
        jPanel5.add(reference);
        reference.setBounds(138, 109, 240, 26);
        jPanel5.add(description);
        description.setBounds(140, 70, 240, 26);

        jButtonUpdate.setBackground(new java.awt.Color(0, 0, 0));
        jButtonUpdate.setFont(new java.awt.Font("Nueva Std", 1, 13)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/imageResp/modiBtn.png"))); // NOI18N
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonUpdate);
        jButtonUpdate.setBounds(527, 296, 126, 50);

        jLabel20.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel20.setText(" Id     ");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(30, 30, 50, 16);
        jPanel5.add(id);
        id.setBounds(138, 25, 240, 26);

        jTable4.setModel(new com.esprit.adapters.ProduitAdapter());
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTable4);

        jPanel5.add(jScrollPane7);
        jScrollPane7.setBounds(510, 0, 355, 278);
        jPanel5.add(jLabel19);
        jLabel19.setBounds(771, 452, 0, 0);
        jPanel5.add(dispo2);
        dispo2.setBounds(140, 410, 240, 26);

        jLabel21.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel21.setText("Prix Vente");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(25, 351, 67, 16);
        jPanel5.add(PriVente);
        PriVente.setBounds(138, 341, 240, 26);

        jLabel22.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel22.setText("Disponible");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(25, 420, 64, 16);
        jPanel5.add(marque);
        marque.setBounds(138, 373, 240, 26);

        jLabel23.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel23.setText("image");
        jPanel5.add(jLabel23);
        jLabel23.setBounds(30, 470, 37, 16);
        jPanel5.add(image);
        image.setBounds(140, 450, 240, 26);

        IMessage.setForeground(new java.awt.Color(255, 0, 0));
        jPanel5.add(IMessage);
        IMessage.setBounds(612, 363, 276, 23);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 1030, 530));

        p.setBackground(new java.awt.Color(204, 51, 255));
        p.setLayout(null);

        jTable1.setModel(new BoutiqueAdapter()
        );
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        p.add(jScrollPane1);
        jScrollPane1.setBounds(3055, 0, 23, 202);

        imageAccProdis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/imageResp/gestionwelcomProduit.jpg"))); // NOI18N
        p.add(imageAccProdis);
        imageAccProdis.setBounds(0, -90, 2060, 920);

        imag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/resp3.png"))); // NOI18N
        p.add(imag);
        imag.setBounds(-290, -90, 1308, 666);

        jPanel1.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 1000, 570));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("designation");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(360, 50, 74, 18);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("taille");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(360, 100, 60, 18);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("reference");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 150, 70, 18);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("couleur");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 200, 80, 14);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("marque");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 50, 70, 18);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("description");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 100, 80, 18);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setText("etat");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(360, 150, 40, 26);

        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        jPanel3.add(a);
        a.setBounds(120, 40, 180, 30);

        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        jPanel3.add(b);
        b.setBounds(120, 90, 180, 30);
        jPanel3.add(c);
        c.setBounds(120, 140, 180, 30);

        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        jPanel3.add(d);
        d.setBounds(120, 190, 180, 30);
        jPanel3.add(e);
        e.setBounds(440, 40, 180, 30);
        jPanel3.add(f);
        f.setBounds(440, 90, 180, 30);

        g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gActionPerformed(evt);
            }
        });
        jPanel3.add(g);
        g.setBounds(780, 30, 180, 30);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setText("prixvente");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(690, 40, 70, 20);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/imageResp/ajouterbtn.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(270, 290, 145, 60);

        IMessage1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(IMessage1);
        IMessage1.setBounds(612, 363, 276, 23);

        g6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g6ActionPerformed(evt);
            }
        });
        jPanel3.add(g6);
        g6.setBounds(440, 140, 180, 30);

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel24.setText("marque");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(690, 90, 70, 20);

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel25.setText("disponible");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(690, 140, 80, 20);

        jLabel26.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel26.setText("image");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(730, 200, 80, 20);

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel28.setText("prixdachat");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(360, 190, 70, 20);

        g7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g7ActionPerformed(evt);
            }
        });
        jPanel3.add(g7);
        g7.setBounds(780, 90, 180, 30);

        g8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g8ActionPerformed(evt);
            }
        });
        jPanel3.add(g8);
        g8.setBounds(780, 140, 180, 30);

        g9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g9ActionPerformed(evt);
            }
        });
        jPanel3.add(g9);
        g9.setBounds(560, 360, 180, 30);

        g12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g12ActionPerformed(evt);
            }
        });
        jPanel3.add(g12);
        g12.setBounds(440, 180, 180, 30);

        addImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/imageResp/ajouterbtn.png"))); // NOI18N
        addImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageActionPerformed(evt);
            }
        });
        jPanel3.add(addImage);
        addImage.setBounds(800, 340, 140, 60);

        jLImage.setText("jLabel30");
        jPanel3.add(jLImage);
        jLImage.setBounds(660, 230, 160, 110);
        jPanel3.add(pic3);
        pic3.setBounds(180, 30, 520, 590);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 1060, 410));

        panel_stat.setLayout(null);
        jPanel1.add(panel_stat, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 700, 500));

        panel_image_deroulante.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_image_deroulanteLayout = new javax.swing.GroupLayout(panel_image_deroulante);
        panel_image_deroulante.setLayout(panel_image_deroulanteLayout);
        panel_image_deroulanteLayout.setHorizontalGroup(
            panel_image_deroulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        panel_image_deroulanteLayout.setVerticalGroup(
            panel_image_deroulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jPanel1.add(panel_image_deroulante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 660, 560));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/imageResp/supprimerBtn.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable2.setModel(new com.esprit.adapters.ProduitAdapter());
        jScrollPane5.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 60, 960, 560));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jTextSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSearch1ActionPerformed(evt);
            }
        });

        search_butn1.setBackground(new java.awt.Color(0, 0, 0));
        search_butn1.setForeground(new java.awt.Color(255, 255, 255));
        search_butn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/imageResp/rechercherBtn.png"))); // NOI18N
        search_butn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_butn1ActionPerformed(evt);
            }
        });

        jTable3.setModel(new com.esprit.adapters.ProduitAdapter());
        jScrollPane6.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jTextSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(search_butn1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(619, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(437, 437, 437)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(254, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_butn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(353, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 120, 990, 520));

        backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/resp3.png"))); // NOI18N
        jPanel1.add(backround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1308, 666));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
      
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
       
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
p.hide();
jPanel4.hide();
        jPanel5.show();
         jPanel3.hide();
         panel_image_deroulante.hide();
         panel_stat.hide();

         jPanel6.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/com/esprit/imageResp/modifier.png"));
        jButton2.setIcon(i);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
         ImageIcon i = new ImageIcon(getClass().getResource("/com/esprit/imageResp/modiNoir.png"));
        jButton2.setIcon(i);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        p.show();
         jPanel3.hide();
       jPanel4.hide();
      jPanel5.hide();
         jPanel6.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 p.hide();
        jPanel5.hide();
         jPanel3.show();
         jPanel4.hide();
         jPanel6.hide();
         panel_image_deroulante.hide();
         panel_stat.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        ImageIcon i = new ImageIcon(getClass().getResource("/com/esprit/imageResp/AjouterR.png"));
        jButton3.setIcon(i);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
       ImageIcon i = new ImageIcon(getClass().getResource("/com/esprit/imageResp/AjouterNoir.png"));
        jButton3.setIcon(i);
    }//GEN-LAST:event_jButton3MouseExited

    private void search_butnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_butnActionPerformed
        // TODO add your handling code here:
        // jTable1.setModel(new ProduitAdapter(new ProduitDao().findProduitByCouleur(jTextSearch.getText())));

        if (!jTextSearch.getText().equals("")) {

            jTable1.setModel(new BoutiqueAdapter(new BoutiqueDao().getAllByKey(jTextSearch.getText())));
            // jTable1.setModel(new BoutiqueAdapter(new BoutiqueDao().findProduitByCouleur(jTextSearch.getText())));
            //jScrollPane1.setViewportView(TablePorteur);
        } else {

            showMessageDialog(this, "Vous devez ecrire quelque chose", "Attention", JOptionPane.INFORMATION_MESSAGE);
            jTable1.setModel(new BoutiqueAdapter());
        }
        jTextSearch.setText("");
     
    }//GEN-LAST:event_search_butnActionPerformed

    private void jTextSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSearchActionPerformed

    private void stat_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stat_btnActionPerformed
  
  p.hide();
        jPanel5.hide();
         jPanel3.hide();
 jPanel4.show();
 jPanel6.hide();
 panel_image_deroulante.hide();
 panel_stat.hide();
 
    }//GEN-LAST:event_stat_btnActionPerformed

    private void stat_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stat_btnMouseEntered
       ImageIcon i = new ImageIcon(getClass().getResource("/com/esprit/imageResp/SupprR.png"));
        stat_btn.setIcon(i);
    }//GEN-LAST:event_stat_btnMouseEntered

    private void stat_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stat_btnMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/com/esprit/imageResp/SuppNoir.png"));
        stat_btn.setIcon(i);
    }//GEN-LAST:event_stat_btnMouseExited

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
     
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
      Page_resp_1 es1  = new Page_resp_1();
        //nom de la classe
        es1.setVisible(true);
        
        es1.setLocationRelativeTo(null);
        es1.setVisible(true);
        this.setVisible(false);  
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        if (!description.getText().trim().equals("")) {
            String r0 = id.getText();
            int v0 = Integer.parseInt(r0);
            String v1 = description.getText();
            String v2 = reference.getText();
            String r = couleur.getText();
            String designation1 = designation22.getText();
            String Taille = size.getText();
            String Etat= Dispo1.getText();
            String Prixdachat=PrAchat.getText();
            String Prixvente=PriVente.getText();
            String Marque=marque.getText();
            String Disponible=dispo2.getText();
            String Img=image.getText();

            ProduitDao produitDao = new ProduitDao();
            Produit pr = new Produit();
            pr.setId(v0);
            pr.setDescription(v1);
            pr.setReference(v2);
            pr.setCouleur(r);
            pr.setDesignation(designation1);
            pr.setTaille(Taille);
            pr.setEtat(Etat);
            pr.setPrixdachat(Float.valueOf(Prixdachat));
            pr.setMarque(Marque);
            pr.setPrixvente(Float.valueOf(Prixvente));

            pr.setDisponible(Disponible);
            pr.setimg(Img);
            // ???????????????? p.setQuantit(resultat.getInt(15));
            /*ag.setALogin(v1);
            ag.setAPassword(v2);
            ag.setCin(v3);
            ag.setDateCin(r2);
            ag.setEmail(v5);
            ag.setNom(v6);
            ag.setPrenom(v7);
            ag.setType(v8);
            ag.setId(v0);*/
            produitDao.updateProduit(pr);
            JOptionPane.showMessageDialog(null, "Produit modifié avec succes", ":D", JOptionPane.INFORMATION_MESSAGE);
            jTable4.setModel(new ProduitAdapter());
            jTable1.setModel(new ProduitAdapter());
            jTable4.setModel(new ProduitAdapter());

            description.setText("");
            reference.setText("");
            couleur.setText("");
            designation22.setText("");
            size.setText("");
            PrAchat.setText("");
            dispo2.setText("");
            id.setText("");
            designation22.setText("");
            size.setText("");
            Dispo1.setText("");
            PrAchat.setText("");
            PriVente.setText("");
            marque.setText("");
            dispo2.setText("");
            image.setText("");

            System.out.println("utiliseuur modifié");
        } else {
           IMessage.setText(" esem produit 5aliteha fergha sahbi (modification) ");
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        id.setText(jTable4.getValueAt(jTable4.getSelectedRow(), 0).toString());
        description.setText(jTable4.getValueAt(jTable4.getSelectedRow(), 1).toString());
        reference.setText(jTable4.getValueAt(jTable4.getSelectedRow(), 2).toString());
        couleur.setText(jTable4.getValueAt(jTable4.getSelectedRow(), 3).toString());
        Produit produit =new ProduitDao().findProduitById(Integer.parseInt(id.getText()));
        designation22.setText(produit.getDesignation());
        size.setText(produit.getTaille());
        Dispo1.setText(produit.isEtat()+"");
        PrAchat.setText(produit.getPrixdachat()+"");
        PriVente.setText(produit.getPrixvente()+"");
        marque.setText(produit.getMarque()+"");
        dispo2.setText(produit.getDisponible()+"");
        image.setText(produit.getImg()+"");
        //combo1.setSelectedItem(jTable4.getValueAt(jTable4.getSelectedRow(), 8).toString());
    }//GEN-LAST:event_jTable4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/com/esprit/imageResp/modifier.png"));
        jButton2.setIcon(i);
        p.hide();
        jPanel5.show();
         jPanel3.hide();
         jPanel6.hide();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
         ImageIcon i = new ImageIcon(getClass().getResource("/com/esprit/imageResp/modifier.png"));
        jButton2.setIcon(i);
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       ImageIcon i = new ImageIcon(getClass().getResource("/com/esprit/imageResp/AjouterR.png"));
        jButton3.setIcon(i);
        p.hide();
        jPanel5.hide();
        jPanel3.show();
        jPanel6.hide();
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    private void gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (!a.getText().trim().equals("")) {
            String v1 = a.getText();
            String v2 = b.getText();
            String r = c.getText();
            //int v3 = Integer.parseInt(r);
            String r2 = d.getText();

            String v5 = e.getText();
            String v6 = f.getText();
            String v7 = g6.getText();
            String v8 = g12.getText();
            String v9 = g.getText();
            String v10 = g7.getText();
            String v11 = g8.getText();
            String v12 = "src/com/esprit/image/"+g9.getText();
            //Object u = combo.getSelectedItem();
            // String v8 = u.toString();

            ProduitDao produitDao = new ProduitDao();
            Produit pr = new Produit();
            pr.setMarque(v1);

            pr.setDescription(v2);
            pr.setReference(r);
            pr.setCouleur(r2);
            pr.setDesignation(v5);
            pr.setTaille(v6);
           // pr.setEtat(Boolean.valueOf(v6));
            pr.setPrixdachat(Float.valueOf(v8));
            pr.setPrixvente(Float.valueOf(v9));
            pr.setMarque(v10);
            pr.setDisponible(v11);
            pr.setimg(v12);

            produitDao.addProduit(pr);
            JOptionPane.showMessageDialog(null, "Agent ajoutĂ© avec succes", ":D", JOptionPane.INFORMATION_MESSAGE);
            jTable4.setModel(new ProduitAdapter());
            jTable1.setModel(new ProduitAdapter());
            jTable4.setModel(new ProduitAdapter());

            a.setText("");
            b.setText("");
            c.setText("");
            d.setText("");
            e.setText("");
            f.setText("");
            g.setText("");

            g6.setText("");
            g12.setText("");

            g7.setText("");
            g8.setText("");
            g9.setText("");

            System.out.println("utiliseuur crĂ©Ă©");
        } else {
            IMessage.setText(" marque 5aliteha fergha 7ot esmaha ;)  ");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void g6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g6ActionPerformed

    private void g7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g7ActionPerformed

    private void g8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g8ActionPerformed

    private void g9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g9ActionPerformed

    private void g12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g12ActionPerformed

    private void addImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f =chooser.getSelectedFile();
        String filename2 = null;
        filename2 = f.getName();
        String filename =f.getAbsolutePath().toString();
        ImageIcon c= new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(jLImage.getWidth(),jLImage.getHeight() , Image.SCALE_DEFAULT));

        jLImage.setIcon(c);
        g9.setText(filename2);
        Image  img =c.getImage();

        BufferedImage bufferedImage = new BufferedImage(c.getIconHeight(),c.getIconWidth(),BufferedImage.TYPE_INT_RGB);
        //BufferedImage bimage = new BufferedImage(img.getWidth(null), img.getHeight(null), BufferedImage.TYPE_INT_ARGB);

        Graphics g = bufferedImage.createGraphics();
        g.drawImage(img, 0, 0, null);
        g.dispose();
        String s=getClass().getResource("/com/esprit/image/").toString();
        s=s.substring(5, s.length());
        s=s.substring(0, s.length()-31);
        s=s+"src/com/esprit/image/";
        try {
            //getClass().getResource("/com/esprit/image/add_256 copie.png")
            System.out.println(s+filename2);
            ImageIO.write(bufferedImage, "jpg",new File(s+filename2));
        } catch (IOException ex) {
            Logger.getLogger(Page_resp_11.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addImageActionPerformed

    private void stat_btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stat_btn1MouseExited
         ImageIcon i = new ImageIcon(getClass().getResource("/com/esprit/imageResp/RechercherN.png"));
     
        stat_btn1.setIcon(i);// TODO add your handling code here:
    }//GEN-LAST:event_stat_btn1MouseExited

    private void stat_btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stat_btn1MouseEntered
         ImageIcon i = new ImageIcon(getClass().getResource("/com/esprit/imageResp/RechercherR.png"));
        stat_btn1.setIcon(i);        // TODO add your handling code here:
    }//GEN-LAST:event_stat_btn1MouseEntered

    private void stat_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stat_btn1ActionPerformed
     ImageIcon i = new ImageIcon(getClass().getResource("/com/esprit/imageResp/RechercherR.png"));
        stat_btn1.setIcon(i); 
        p.hide();
        jPanel5.hide();
         jPanel3.hide();
 jPanel4.hide();
 jPanel6.show();
 panel_image_deroulante.hide();
 panel_stat.hide();
    }//GEN-LAST:event_stat_btn1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ProduitDao agdao = new ProduitDao();

        new ProduitDao().removeProduitById(Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString()));

        jTable2.setModel(new ProduitAdapter());
        jTable1.setModel(new ProduitAdapter());
        jTable4.setModel(new ProduitAdapter());

        JOptionPane.showMessageDialog(null, "Agent supprimĂ© avec succes", ":D", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void stat_btn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stat_btn2MouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/com/esprit/imageResp/stat.png"));
     
        stat_btn2.setIcon(i);// TODO add your handling code here:
    }//GEN-LAST:event_stat_btn2MouseExited

    private void stat_btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stat_btn2MouseEntered
    ImageIcon i = new ImageIcon(getClass().getResource("/com/esprit/imageResp/statR.png"));
     
        stat_btn2.setIcon(i);// TODO add your handling code here:
    }//GEN-LAST:event_stat_btn2MouseEntered

    private void stat_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stat_btn2ActionPerformed
  p.hide();
        jPanel5.hide();
         jPanel3.hide();
 jPanel4.hide();
 jPanel6.hide();
      
        try {
            DefaultPieDataset PieDataset = new DefaultPieDataset();
            ProduitDao md = new ProduitDao();
            List<Produit> moyens = new Vector<>();
            moyens = md.getProduitsGroupByStocknour();

            for (int i = 0; i < moyens.size(); i++) {
                // System.out.println(moyens.get(i).getCategories1());
                PieDataset.setValue(moyens.get(i).getCategories(), md.countnour(moyens.get(i).getId()));
            }
            JFreeChart chart = ChartFactory.createPieChart3D("Répartition des produits selon catégorie", PieDataset, true, true, true);
            chart.setBackgroundPaint((new Color(0xFFFFFF)));//********

            PiePlot p = (PiePlot) chart.getPlot();
            p.setBackgroundPaint((new Color(0xFFE4C4)));//************
            //p.setForegroundAlpha(TOP_ALIGNMENT);

            ChartPanel frame = new ChartPanel(chart);
            frame.setVisible(true);
            frame.setSize(700, 480);
            panel_stat.add(frame);

        } catch (SQLException ex) {
            Logger.getLogger(fos_user.class.getName()).log(Level.SEVERE, null, ex);
        }
        panel_image_deroulante.setVisible(false);
        p.setVisible(false);
        
        panel_stat.setVisible(true);
       
    }//GEN-LAST:event_stat_btn2ActionPerformed

    private void jTextSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSearch1ActionPerformed

    private void search_butn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_butn1ActionPerformed
        // TODO add your handling code here:
        // jTable1.setModel(new ProduitAdapter(new ProduitDao().findProduitByCouleur(jTextSearch.getText())));
        if (!jTextSearch.getText().equals("")) {

            jTable1.setModel(new ProduitAdapter(new ProduitDao().getAllByKey(jTextSearch.getText())));
            //jScrollPane1.setViewportView(TablePorteur);
        } else {

            showMessageDialog(this, "Vous devez ecrire quelque chose", "Attention", JOptionPane.INFORMATION_MESSAGE);
            jTable1.setModel(new ProduitAdapter());
        }
        jTextSearch.setText("");
    }//GEN-LAST:event_search_butn1ActionPerformed
 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
                UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page_resp_12n.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page_resp_12n.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page_resp_12n.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page_resp_12n.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Page_resp_12n es = new Page_resp_12n();
                es.setSize(1308, 666);
                es.setLocationRelativeTo(null);
                es.setVisible(true);
//                Projet1 pr = new Projet1();
//            pr.setVisible(true);
//            pr.setSize(780,400);
//            pr.setLocationRelativeTo(null);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dispo1;
    private javax.swing.JLabel IMessage;
    private javax.swing.JLabel IMessage1;
    private javax.swing.JTextField PrAchat;
    private javax.swing.JTextField PriVente;
    private javax.swing.JTextField a;
    private javax.swing.JButton addImage;
    private javax.swing.JTextField b;
    private javax.swing.JLabel backround;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField c;
    private javax.swing.JTextField couleur;
    private javax.swing.JTextField d;
    private javax.swing.JTextField description;
    private javax.swing.JTextField designation22;
    private javax.swing.JTextField dispo2;
    private javax.swing.JTextField e;
    private javax.swing.JTextField f;
    private javax.swing.JTextField g;
    private javax.swing.JTextField g12;
    private javax.swing.JTextField g6;
    private javax.swing.JTextField g7;
    private javax.swing.JTextField g8;
    private javax.swing.JTextField g9;
    private javax.swing.JTextField id;
    private javax.swing.JLabel imag;
    private javax.swing.JTextField image;
    private javax.swing.JLabel imageAccProdis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLImage;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextSearch;
    private javax.swing.JTextField jTextSearch1;
    private javax.swing.JTextField marque;
    private javax.swing.JPanel p;
    private javax.swing.JPanel panel_image_deroulante;
    private javax.swing.JPanel panel_stat;
    private javax.swing.JLabel pic3;
    private javax.swing.JTextField reference;
    private javax.swing.JButton search_butn;
    private javax.swing.JButton search_butn1;
    private javax.swing.JTextField size;
    private javax.swing.JButton stat_btn;
    private javax.swing.JButton stat_btn1;
    private javax.swing.JButton stat_btn2;
    // End of variables declaration//GEN-END:variables
}
