package com.esprit.GUI;
import com.esprit.DAO.ProduitDao;
import com.esprit.adapters.ProduitAdapter;
import com.esprit.entites.Produit;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.UIManager;
import org.jfree.ui.RefineryUtilities;
/**
 *
 * @author pc
 */
public class Page_resp_11 extends javax.swing.JFrame {

    /**
     * Creates new form Respensable_page
     */
     final PieChart demo = new PieChart("Test de la couverture ");
    public Page_resp_11() throws IOException {
        initComponents();
        
        demo.pack();
        RefineryUtilities.centerFrameOnScreen(demo);
        demo.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        stat = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        f = new javax.swing.JTextField();
        g = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        IMessage = new javax.swing.JLabel();
        g6 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        g7 = new javax.swing.JTextField();
        g8 = new javax.swing.JTextField();
        g9 = new javax.swing.JTextField();
        g12 = new javax.swing.JTextField();
        addImage = new javax.swing.JButton();
        jLImage = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTextSearch = new javax.swing.JTextField();
        search_butn = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        g1 = new javax.swing.JTextField();
        f1 = new javax.swing.JTextField();
        e1 = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();
        c1 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        h1 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        g2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        g3 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        g4 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        g5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/gerer_btn.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 255, 63));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/produit1.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 255, 63));

        stat.setOpaque(false);
        stat.setLayout(null);

        jTabbedPane2.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        jTabbedPane2.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/image/23314007-3D-r-alistes-illustration-vectorielle-d-un-bouton-en-m-tal-carr-avec-un-panier-ic-ne-de-suppression--Banque-d'images (1).jpg"))); // NOI18N
        jButton4.setText("supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable2.setModel(new com.esprit.adapters.ProduitAdapter());
        jScrollPane5.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jButton4)))
                .addContainerGap(336, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Supprimer produit", jPanel4);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("designation");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(360, 50, 74, 18);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("taille");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(360, 100, 60, 18);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("reference");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 150, 70, 18);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("couleur");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 200, 80, 14);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("marque");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 50, 70, 18);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("description");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 100, 80, 18);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setText("etat");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(360, 150, 40, 26);

        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        jPanel3.add(a);
        a.setBounds(120, 40, 180, 30);

        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        jPanel3.add(b);
        b.setBounds(120, 90, 180, 30);
        jPanel3.add(c);
        c.setBounds(120, 140, 180, 30);

        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        jPanel3.add(d);
        d.setBounds(120, 190, 180, 30);
        jPanel3.add(e);
        e.setBounds(440, 40, 180, 30);
        jPanel3.add(f);
        f.setBounds(440, 90, 180, 30);

        g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gActionPerformed(evt);
            }
        });
        jPanel3.add(g);
        g.setBounds(780, 30, 180, 30);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setText("prixvente");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(690, 40, 70, 20);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/image/add_256 copie.png"))); // NOI18N
        jButton3.setText("Ajouter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(270, 290, 145, 60);

        IMessage.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(IMessage);
        IMessage.setBounds(612, 363, 276, 23);

        g6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g6ActionPerformed(evt);
            }
        });
        jPanel3.add(g6);
        g6.setBounds(440, 140, 180, 30);

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel24.setText("marque");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(690, 90, 70, 20);

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel25.setText("disponible");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(690, 140, 80, 20);

        jLabel26.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel26.setText("image");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(660, 190, 80, 20);

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        jLabel28.setText("prixdachat");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(360, 190, 70, 20);

        g7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g7ActionPerformed(evt);
            }
        });
        jPanel3.add(g7);
        g7.setBounds(780, 90, 180, 30);

        g8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g8ActionPerformed(evt);
            }
        });
        jPanel3.add(g8);
        g8.setBounds(780, 140, 180, 30);

        g9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g9ActionPerformed(evt);
            }
        });
        jPanel3.add(g9);
        g9.setBounds(760, 310, 180, 30);

        g12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g12ActionPerformed(evt);
            }
        });
        jPanel3.add(g12);
        g12.setBounds(440, 180, 180, 30);

        addImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/image/add_256 copie.png"))); // NOI18N
        addImage.setText("add image");
        addImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageActionPerformed(evt);
            }
        });
        jPanel3.add(addImage);
        addImage.setBounds(590, 290, 140, 60);

        jLImage.setText("jLabel30");
        jPanel3.add(jLImage);
        jLImage.setBounds(710, 190, 160, 110);

        jTabbedPane2.addTab("Ajout produit", jPanel3);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jTextSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSearchActionPerformed(evt);
            }
        });

        search_butn.setBackground(new java.awt.Color(0, 0, 0));
        search_butn.setForeground(new java.awt.Color(255, 255, 255));
        search_butn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/image/rechercher-icone-8124-32.png"))); // NOI18N
        search_butn.setText("search");
        search_butn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_butnActionPerformed(evt);
            }
        });

        jTable1.setModel(new com.esprit.adapters.ProduitAdapter());
        jScrollPane6.setViewportView(jTable1);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("statistique");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jTextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_butn, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addContainerGap(686, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(437, 437, 437)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(321, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_butn))
                .addGap(31, 31, 31)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab(" recherche produit ", jPanel6);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel11.setText("description");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(20, 90, 68, 16);

        jLabel12.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel12.setText("reference");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(25, 118, 59, 16);

        jLabel13.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel13.setText("couleur");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(25, 162, 46, 16);

        jLabel14.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel14.setText("designation");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(25, 206, 70, 16);

        jLabel15.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel15.setText("taille");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(25, 250, 31, 16);

        jLabel16.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel16.setText("etat");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(25, 287, 24, 16);

        jLabel17.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel17.setText("prixdachat");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(20, 330, 65, 16);

        jLabel18.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel18.setText("marque");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(25, 373, 47, 16);
        jPanel5.add(g1);
        g1.setBounds(138, 277, 87, 26);
        jPanel5.add(f1);
        f1.setBounds(138, 309, 87, 26);
        jPanel5.add(e1);
        e1.setBounds(138, 241, 87, 26);
        jPanel5.add(d1);
        d1.setBounds(138, 197, 87, 26);
        jPanel5.add(c1);
        c1.setBounds(138, 153, 87, 26);
        jPanel5.add(b1);
        b1.setBounds(138, 109, 87, 26);
        jPanel5.add(a1);
        a1.setBounds(138, 78, 87, 26);

        jButtonUpdate.setBackground(new java.awt.Color(0, 0, 0));
        jButtonUpdate.setFont(new java.awt.Font("Nueva Std", 1, 13)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/esprit/image/refresh_button_link_save_submit_search_pause_icon copie.png"))); // NOI18N
        jButtonUpdate.setText("update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonUpdate);
        jButtonUpdate.setBounds(527, 296, 126, 71);

        jLabel20.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel20.setText("id");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(25, 34, 11, 16);
        jPanel5.add(h1);
        h1.setBounds(138, 25, 87, 26);

        jTable4.setModel(new com.esprit.adapters.ProduitAdapter());
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTable4);

        jPanel5.add(jScrollPane7);
        jScrollPane7.setBounds(510, 0, 355, 278);
        jPanel5.add(jLabel19);
        jLabel19.setBounds(771, 452, 0, 0);
        jPanel5.add(g2);
        g2.setBounds(138, 420, 87, 26);

        jLabel21.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel21.setText("prixvente");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(25, 351, 67, 16);
        jPanel5.add(g3);
        g3.setBounds(138, 341, 87, 26);

        jLabel22.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel22.setText("disponible");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(25, 420, 62, 16);
        jPanel5.add(g4);
        g4.setBounds(138, 373, 87, 26);

        jLabel23.setFont(new java.awt.Font("Nueva Std", 0, 13)); // NOI18N
        jLabel23.setText("image");
        jPanel5.add(jLabel23);
        jLabel23.setBounds(288, 420, 37, 16);
        jPanel5.add(g5);
        g5.setBounds(386, 420, 87, 26);

        jTabbedPane2.addTab("update produit", jPanel5);

        stat.add(jTabbedPane2);
        jTabbedPane2.setBounds(-10, 10, 1080, 500);

        jPanel1.add(stat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 1070, 510));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/resp2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
    ImageIcon i =new ImageIcon(getClass().getResource("/Icon/gerer2_btn.png"));
      jButton1.setIcon(i);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        ImageIcon i =new ImageIcon(getClass().getResource("/Icon/gerer_btn.png"));
      jButton1.setIcon(i);
       // System.out.println("getClass().getResource(\"/Icon/gerer_btn.png\"");
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        ImageIcon i =new ImageIcon(getClass().getResource("/Icon/produit2.png"));
      jButton2.setIcon(i);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        ImageIcon i =new ImageIcon(getClass().getResource("/Icon/produit1.png"));
      jButton2.setIcon(i);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Page_resp_1 es=new Page_resp_1(); //nom de la classe
        es.setVisible(true);
        es.setSize(1308,566);
        es.setLocationRelativeTo(null);
        es.setVisible(true);
        this.setVisible(false);  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ProduitDao agdao = new ProduitDao();

        new ProduitDao().removeProduitById(Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString()));

        jTable2.setModel(new ProduitAdapter());
        jTable1.setModel(new ProduitAdapter());
        jTable4.setModel(new ProduitAdapter());

        JOptionPane.showMessageDialog(null, "Agent supprimé avec succes", ":D", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    private void gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!a.getText().trim().equals("")) {
            String v1 = a.getText();
            String v2 = b.getText();
            String r = c.getText();
            //int v3 = Integer.parseInt(r);
            String r2 = d.getText();

            String v5 = e.getText();
            String v6 = f.getText();
            String v7 = g6.getText();
            String v8 = g12.getText();
            String v9 = g.getText();
            String v10 = g7.getText();
            String v11 = g8.getText();
            String v12 = "src/com/esprit/image/"+g9.getText();
            //Object u = combo.getSelectedItem();
            // String v8 = u.toString();

            ProduitDao produitDao = new ProduitDao();
            Produit pr = new Produit();
            pr.setMarque(v1);

            pr.setDescription(v2);
            pr.setReference(r);
            pr.setCouleur(r2);
            pr.setDesignation(v5);
            pr.setTaille(v6);
            pr.setEtat(v6);
            pr.setPrixdachat(Float.valueOf(v8));
            pr.setPrixvente(Float.valueOf(v9));
            pr.setMarque(v10);
            pr.setDisponible(v11);
            pr.setimg(v12);

            produitDao.addProduit(pr);
            JOptionPane.showMessageDialog(null, "Agent ajouté avec succes", ":D", JOptionPane.INFORMATION_MESSAGE);
            jTable2.setModel(new ProduitAdapter());
            jTable1.setModel(new ProduitAdapter());
            jTable4.setModel(new ProduitAdapter());

            a.setText("");
            b.setText("");
            c.setText("");
            d.setText("");
            e.setText("");
            f.setText("");
            g.setText("");

            g6.setText("");
            g12.setText("");

            g7.setText("");
            g8.setText("");
            g9.setText("");

            System.out.println("utiliseuur créé");
        } else {
            IMessage.setText(" marque 5aliteha fergha 7ot esmaha ;)  ");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void g6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g6ActionPerformed

    private void g7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g7ActionPerformed

    private void g8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g8ActionPerformed

    private void g9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g9ActionPerformed

    private void g12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g12ActionPerformed

    private void addImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f =chooser.getSelectedFile();
String filename2 = null;
         filename2 = f.getName();
        String filename =f.getAbsolutePath().toString();
        ImageIcon c= new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(jLImage.getWidth(),jLImage.getHeight() , Image.SCALE_DEFAULT));

        jLImage.setIcon(c);
        g9.setText(filename2);
        Image  img =c.getImage();

        BufferedImage bufferedImage = new BufferedImage(c.getIconHeight(),c.getIconWidth(),BufferedImage.TYPE_INT_RGB);
        //BufferedImage bimage = new BufferedImage(img.getWidth(null), img.getHeight(null), BufferedImage.TYPE_INT_ARGB);

        
        Graphics g = bufferedImage.createGraphics();
        g.drawImage(img, 0, 0, null);
        g.dispose();
        String s=getClass().getResource("/com/esprit/image/").toString();
        s=s.substring(5, s.length());
         s=s.substring(0, s.length()-31);
         s=s+"src/com/esprit/image/";
         try {
             //getClass().getResource("/com/esprit/image/add_256 copie.png")
             System.out.println(s+filename2);
             ImageIO.write(bufferedImage, "jpg",new File(s+filename2));
         } catch (IOException ex) {
             Logger.getLogger(Page_resp_11.class.getName()).log(Level.SEVERE, null, ex);
         }

    }//GEN-LAST:event_addImageActionPerformed

    private void jTextSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSearchActionPerformed

    private void search_butnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_butnActionPerformed
        // TODO add your handling code here:
        // jTable1.setModel(new ProduitAdapter(new ProduitDao().findProduitByCouleur(jTextSearch.getText())));
        if (!jTextSearch.getText().equals("")) {

            jTable1.setModel(new ProduitAdapter(new ProduitDao().getAllByKey(jTextSearch.getText())));
            //jScrollPane1.setViewportView(TablePorteur);
        } else {

            showMessageDialog(this, "Vous devez ecrire quelque chose", "Attention", JOptionPane.INFORMATION_MESSAGE);
            jTable1.setModel(new ProduitAdapter());
        }
        jTextSearch.setText("");
    }//GEN-LAST:event_search_butnActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        if (!a1.getText().trim().equals("")) {
            String r0 = h1.getText();
            int v0 = Integer.parseInt(r0);
            String v1 = a1.getText();
            String v2 = b1.getText();
            String r = c1.getText();
            String designation = d1.getText();
            String Taille = e1.getText();
            String Etat= g1.getText();
            String Prixdachat=f1.getText();
            String Prixvente=g3.getText();
            String Marque=g4.getText();
            String Disponible=g2.getText();
            String Img=g5.getText();

            ProduitDao produitDao = new ProduitDao();
            Produit pr = new Produit();
            pr.setId(v0);
            pr.setDescription(v1);
            pr.setReference(v2);
            pr.setCouleur(r);
            pr.setDesignation(designation);
            pr.setTaille(Taille);
            pr.setEtat(Etat);
            pr.setPrixdachat(Float.valueOf(Prixdachat));
            pr.setMarque(Marque);
            pr.setPrixvente(Float.valueOf(Prixvente));

            pr.setDisponible(Disponible);
            pr.setimg(Img);
            // ???????????????? p.setQuantit(resultat.getInt(15));
            /*ag.setALogin(v1);
            ag.setAPassword(v2);
            ag.setCin(v3);
            ag.setDateCin(r2);
            ag.setEmail(v5);
            ag.setNom(v6);
            ag.setPrenom(v7);
            ag.setType(v8);
            ag.setId(v0);*/
            produitDao.updateProduit(pr);
            JOptionPane.showMessageDialog(null, "Produit modifié avec succes", ":D", JOptionPane.INFORMATION_MESSAGE);
            jTable2.setModel(new ProduitAdapter());
            jTable1.setModel(new ProduitAdapter());
            jTable4.setModel(new ProduitAdapter());

            a1.setText("");
            b1.setText("");
            c1.setText("");
            d1.setText("");
            e1.setText("");
            f1.setText("");
            g1.setText("");
            h1.setText("");
            d1.setText("");
            e1.setText("");
            g1.setText("");
            f1.setText("");
            g3.setText("");
            g4.setText("");
            g2.setText("");
            g5.setText("");

            System.out.println("utiliseuur modifié");
        } else {
            IMessage.setText(" esem l'agent 5aliteha fergha sahbi (modification) ");
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        h1.setText(jTable4.getValueAt(jTable4.getSelectedRow(), 0).toString());
        a1.setText(jTable4.getValueAt(jTable4.getSelectedRow(), 1).toString());
        b1.setText(jTable4.getValueAt(jTable4.getSelectedRow(), 2).toString());
        c1.setText(jTable4.getValueAt(jTable4.getSelectedRow(), 3).toString());
        Produit produit =new ProduitDao().findProduitById(Integer.parseInt(h1.getText()));
        d1.setText(produit.getDesignation());
        e1.setText(produit.getTaille());
        g1.setText(produit.isEtat()+"");
        f1.setText(produit.getPrixdachat()+"");
        g3.setText(produit.getPrixvente()+"");
        g4.setText(produit.getMarque()+"");
        g2.setText(produit.getDisponible()+"");
        g5.setText(produit.getImg()+"");
        //combo1.setSelectedItem(jTable4.getValueAt(jTable4.getSelectedRow(), 8).toString());
    }//GEN-LAST:event_jTable4MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         try {
             final PieChart demo = new PieChart("Test de la couverture ");
             demo.pack();
             RefineryUtilities.centerFrameOnScreen(demo);
             demo.setVisible(true);
         } catch (IOException ex) {
             Logger.getLogger(Page_resp_11.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Login e = new Login();
     this.setVisible(false);
     e.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
                 UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page_resp_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page_resp_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page_resp_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page_resp_11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
                try {
                    Page_resp_11 es=new Page_resp_11();
                    es.setSize(1308,566);
                    es.setLocationRelativeTo(null);
                    es.setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Page_resp_11.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMessage;
    private javax.swing.JTextField a;
    private javax.swing.JTextField a1;
    private javax.swing.JButton addImage;
    private javax.swing.JTextField b;
    private javax.swing.JTextField b1;
    private javax.swing.JTextField c;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField d;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField e;
    private javax.swing.JTextField e1;
    private javax.swing.JTextField f;
    private javax.swing.JTextField f1;
    private javax.swing.JTextField g;
    private javax.swing.JTextField g1;
    private javax.swing.JTextField g12;
    private javax.swing.JTextField g2;
    private javax.swing.JTextField g3;
    private javax.swing.JTextField g4;
    private javax.swing.JTextField g5;
    private javax.swing.JTextField g6;
    private javax.swing.JTextField g7;
    private javax.swing.JTextField g8;
    private javax.swing.JTextField g9;
    private javax.swing.JTextField h1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLImage;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextSearch;
    private javax.swing.JButton search_butn;
    private javax.swing.JPanel stat;
    // End of variables declaration//GEN-END:variables
}
